version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore CustomerApp.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build CustomerApp.csproj

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./ CustomerApp.csproj

artifacts:
  files:
    - '**/*'